Динамический индекс = 
VAR SelectedWaiting = AVERAGE('Ожидание'[Ожидание])
RETURN
AVERAGEX(
    KEEPFILTERS(
        SUMMARIZE('Лист1', 'Лист1'[Город], 'Лист1'[Категория])
    ),
    VAR AdjustedTime = 
        (CALCULATE(AVERAGE('Лист1'[Ожидание])) * SelectedWaiting + CALCULATE(AVERAGE('Лист1'[Штраф])) + CALCULATE(AVERAGE('Лист1'[Чистое время в пути (мин)]))) -- т.к. через SUM суммировались все числа, пришлось сделать упрощение и остановиться на среднем
    RETURN
    SWITCH(TRUE(),
        AdjustedTime < 10, 12,
        AdjustedTime < 20, 11,
        AdjustedTime < 30, 10,
        AdjustedTime < 40, 9,
        AdjustedTime < 50, 8,
        AdjustedTime < 60, 7,
        AdjustedTime < 70, 6,
        AdjustedTime < 80, 5,
        AdjustedTime < 90, 4,
        AdjustedTime < 100, 3,
        AdjustedTime < 110, 2,
        AdjustedTime < 120, 1,
        0
    )
)
